/*
 * glftv.de
 * Theme Name: GLFtv
 * Description: GLFtv Worpdress Theme
 * Author: GLF goes Mobile Projektgruppe - Dev Team: Ramona Rapp, Sebastian Petöcz, Aileen Völker
 * Version: 1.0
 */

 /*Define global vars */
 var navMain = $('.nav-main');
 var deskNav = $('#navDeskMain');
 var mobNav = $('#navMobileMain');
 var label_left = $(document.createElement('span'));
 var label_right = $(document.createElement('span'));
 var activeItem;
 var expandItem;
 var expandTimeout;
 var mobileNav = false;
 var navDInitialized = false;
 var navMInitialized = false;
 var isChildItem = false;
 var tabsInitialized = false;
 var filterInitialized = false;
 var tileHeightChanged = false;
 var minSlides = true;
 var bigSlides = true;
 var filterHeight;
 var semRangeValue = new Array();
 var semRangeText = ['WS07/08', 'SoSe08', 'WS08/09', 'SoSe09', 'WS09/10', 'SoSe10', 'WS10/11', 'SoSe11', 'WS11/12', 'SoSe12', 'WS12/13', 'SoSe13'];

 $(window).load(function() {
	// init flexslider - img slider
	$('.flexslider').flexslider({
		animation : "slide",
		slideshowSpeed : 7000,
		animationSpeed : 800,
		prevText : " ",
		nextText : " ",
	});

	var body = $('body');
	var pageSendungen = $('.page-template-sendungen-php');
	if ($(body).is($(pageSendungen))) {
		/*Init Filter Range Slider*/
		$('#filter-range-slider').noUiSlider({
			start : [5, 10],
			range : [0, 11],
			step : 1,
			connect : true,
			handles : 2,
			slide : function() {
				semRangeValue = $(this).val();
				createLabels(semRangeValue);
			}
		});
		filterRangeInit();
	}
});
//window.load End

$(document).ready(function() {
	/*************Search Page Functions *****************/
	/* Toggle FilterHeight on search page */
	/*
	var filterBtn = [];
	filterBtn.push($('#filter_clips_btn'));
	filterBtn.push($('#filter_broadcasts_btn'));
	filterBtn.push($('#filter_all_btn'));
	$(filterBtn).each(function() {
	$(this).click(function() {
	toggleSearchFilters(this);
	});
	});
*/
	// Hide ajax loader (generated by daves live search plugin) on inpage search field
	var searchInputInpage = $('.search-field-wrapper').find('input');
	$(searchInputInpage).keyup(function() {
		var loader = $('.search_results_activity_indicator');
		$(loader).hide();
	});
	/*************Search Page Functions End*****************/
	$('.reload-form').click(function() {
		overlayContentToggle();
	});
	var footerLabel = $('footer').find('a');
	$(footerLabel).click(function(e) {
		if ($(this).attr('href') == '#!') {
			e.preventDefault();
		}
	});
	/*call functions */
	detectWidth();
});
/*document.ready end */

$(window).bind('resize', function(e) {
	detectWidth();
});

function detectWidth() {
	var winW = $(window).width();
	var htmlTag = $('html');
	var body = $('body');
	var isSinglePage = $(body).hasClass('single');
	var isInfoPage = $(body).hasClass('page-id-58');
	var isLivePage = $(body).hasClass('page-template-live-php');
	var isSendungsPage = $(body).hasClass('page-template-sendungen-php');
	var isBeitragsPage = $(body).hasClass('page-template-beitraege-php');
	$(navMain).removeAttr('style');
	$('.menu-item').removeAttr('style');

	//show mobile nav, hide desk nav
	if (winW <= 1035 || $(htmlTag).not('.no-touch')) {
		$(body).addClass('mobile');
		mobileNav = true;
	}
	//show mobile nav, hide desk nav
	if (winW > 1035 && $(htmlTag).is('.no-touch')) {
		//set mobile nav on starting state to prevent opening and misaligning
		$(mobNav).removeClass('pushy-open').addClass('pushy-left').removeAttr('style');
		$(body).removeClass('mobile');
		$(body).removeClass('pushy-active').removeAttr('style');
		$(htmlTag).removeClass('pushy-active');
		//remove classes and styles generated by pushy plugin
		$('.content-wrapper').removeClass('container-push').removeAttr('style');
		$('header').removeClass('push-push').removeAttr('style');
		mobileNav = false;
	}
	if (!navMInitialized || !navDInitialized) {
		navFunctions();
	}
	if (winW <= 440) {
		resizeTiles();
	}
	if(winW <= 480){
		if(minSlides){
			var slider = $('.bxslider').bxSlider({
				minSlides: 1,
				maxSlides: 5,
				slideWidth: 407,
			});
			bigSlides = true;
			minSlides= false;
			slider.destroySlider();
			slider.reloadSlider();
		}
	}
	if (winW <= 640) {
		if (!tabsInitialized && isSinglePage || !tabsInitialized && isLivePage || !tabsInitialized && isInfoPage) {
			tabs();
		}
		if (!filterInitialized && isSendungsPage || !filterInitialized && isBeitragsPage) {
			filterToggle();
		}
	}
	if (winW > 640) {
		if (tabsInitialized && isSinglePage || tabsInitialized && isLivePage || tabsInitialized && isInfoPage) {
			removetabs();
		}
		if (filterInitialized && isSendungsPage || filterInitialized && isBeitragsPage) {
			clearFilterToggle();
		}
	}
	if(winW > 480){
		if(bigSlides){
			var slider = $('.bxslider').bxSlider({
				minSlides: 1,
				maxSlides: 5,
				slideWidth: 207,
			});
			bigSlides = false;
			minSlides = true;
			slider.destroySlider();
			slider.reloadSlider();
		}
	}
	if (winW > 440 && tileHeightChanged) {
		$('.tile').removeAttr('style');
	}
}
function navFunctions() {
	if (!mobileNav) {
		navDInitialized = true;
		var DeskMenuItem = $(deskNav).find('.menu-item-has-children');
		$(DeskMenuItem).find('a').click(function() {
			if($(this).parent().hasClass('menu-item-has-children')){
				expandItem = $(this).parent('.menu-item-has-children');
				NavDesktopToggle();
			}
		});
		$('.nav-accordion-header').click(function(){
			expandItem = $(this).parents('.menu-item-has-children');
			NavDesktopToggle();
		});
		NavDesktopToggle();
	}
	if (mobileNav) {
		navMInitialized = true;
		//NavMobileToggle Function is called in pushy.js Plugin
	}
}


/*************Nav Accordion Toggle Functions *****************/
function NavMobileToggle(expandItem) {//NavMobileToggle is called in pushy.js Plugin
	//active Item is the Nav Item which is expanded at the moment the nav clicked
	var menuCollapsibleItem = $(mobNav).find('.menu-item-has-children');
	var currentMenuParent = $(mobNav).find('.menu-item-has-children.current-menu-parent');
	var currentActive = false;
	if ($(menuCollapsibleItem).hasClass('active')) {
		activeItem = $(mobNav).find('.menu-item-has-children.active');
	} else if ($(currentMenuParent).length > 0 && expandItem == null ) {
		activeItem = $(mobNav).find('.menu-item-has-children.current-menu-parent');
		$(activeItem).addClass('active');
		expandItem = activeItem;
		currentActive = true;
	}
	$(activeItem).animate({
		height : "50px"
	}, {
		duration : 300,
		queue : false
	});
	if($(activeItem).attr('id') == $(expandItem).attr('id') && currentActive == false){
		$(activeItem).removeClass('active');
		activeItem = null;
	}
	else{
		$(expandItem).animate({
			height : "146px"
		}, {
			duration : 300,
			queue : false,
		});
		$(activeItem).removeClass('active');
		activeItem = expandItem;
		expandItem = null;
		$(activeItem).addClass('active');
	}
}
/*HOVER NAVI
/* expand hovered Item and collapse former activeItem 
function NavDesktopToggle(mLeave) {
	//active Item is the Nav Item which is expanded
	var menuCollapsibleItem = $(deskNav).find('.menu-item-has-children');
	if ($(menuCollapsibleItem).hasClass('active')) {
		activeItem = $(deskNav).find('.menu-item-has-children.active');
	} else {
		//default activeItem is the one of the currently visited page
		activeItem = $(deskNav).find('.menu-item-has-children.current-menu-parent');
		$(activeItem).addClass('active');
	}
	if ($(activeItem).hasClass('search-btn')) {
		$(activeItem).animate({
			width : "72px"
		}, {
			duration : 300,
			queue : false
		});
		//hide search results and blur input when search item gets collapsed
		searchResHide();
		$(activeItem).css('overflow', 'hidden');
		$('.search-input').blur();
	} else {
		$(activeItem).animate({
			width : "126px"
		}, {
			duration : 300,
			queue : false
		});
	}
	if (isChildItem == true || mLeave == false) {
		if ($(expandItem).hasClass('search-btn')) {
			$(expandItem).animate({
				width : "326px"
			}, {
				duration : 300,
				queue : false,
			});
		} else {
			$(expandItem).animate({
				width : "379px"
			}, {
				duration : 300,
				queue : false,
			});
		}
	}
	$(activeItem).removeClass('active');
	activeItem = expandItem;
	$(activeItem).addClass('active');
}

function stopAnimation() {
	clearTimeout(expandTimeout);
}

/*************Nav Accordion Toggle Functions End *****************/
function NavDesktopToggle() {
	//active Item is the Nav Item which is expanded
	var menuCollapsibleItem = $(deskNav).find('.menu-item-has-children');
	var currentMenuParent = $(deskNav).find('.menu-item-has-children.current-menu-parent');
	var currentActive = false;
	if ($(menuCollapsibleItem).hasClass('active')) {
		activeItem = $(deskNav).find('.menu-item-has-children.active');
	} else if ($(currentMenuParent).length > 0 && expandItem == null) {
		activeItem = $(deskNav).find('.menu-item-has-children.current-menu-parent');
		$(activeItem).addClass('active');
		expandItem = activeItem;
		currentActive = true;
	}
	if ($(activeItem).hasClass('search-btn')) {
		$(activeItem).animate({
			width : "72px"
		}, {
			duration : 300,
			queue : false
		});
		//hide search results and blur input when search item gets collapsed
		searchResHide();
		$(activeItem).css('overflow', 'hidden');
		$('.search-input').blur();
	} else {
		$(activeItem).animate({
			width : "126px"
		}, {
			duration : 300,
			queue : false
		});
	}
	if($(activeItem).attr('id') == $(expandItem).attr('id') && currentActive == false){
		$(activeItem).removeClass('active');
		activeItem = null;
	}
	else{
		if ($(expandItem).hasClass('search-btn')) {
			$(expandItem).animate({
				width : "326px"
			}, {
				duration : 300,
				queue : false,
			});
		} else {
			$(expandItem).animate({
				width : "379px"
			}, {
				duration : 300,
				queue : false,
			});
		}
		$(activeItem).removeClass('active');
		activeItem = expandItem;
		expandItem = null;
		$(activeItem).addClass('active');
	}
}
/*************Search Page Functions *****************/
function searchResHide() {
	var searchRes = $("ul").filter(".dwls_search_results:visible");
	if ($(searchRes).size() > 0) {
		$(searchRes).slideUp(100);
	}
}

/*
function toggleSearchFilters(filterBtn) {
var filterType = $(filterBtn).attr('id');
filterType = filterType.split('_');
var filterWrapper = $('.filter-wrapper');
var filterToggleId = '#filter_' + filterType[1] + '_wrapper';
var filterTypeWrapper = $('.filter-type-wrapper');
var filterWrapperBox = parseInt($(filterWrapper).css('padding-bottom').replace(/[^-\d\.]/g, ''));
var filterToggleBtnHeight = $('.filter-toggle-wrapper').height();
$('.filter-toggle').addClass('hidden');
if ($(filterToggleId).length != 0) {
var filterToggle = $(filterToggleId);
$(filterToggle).removeClass('hidden');
var filterToggleBox = parseInt($(filterToggle).css('margin-top').replace(/[^-\d\.]/g, ''));
filterHeight = filterWrapperBox + filterToggleBtnHeight + $(filterToggle).height() + filterToggleBox + $(filterTypeWrapper).height();
} else {
filterHeight = filterWrapperBox + filterToggleBtnHeight + $(filterTypeWrapper).height();
}
$(filterWrapper).animate({
height : filterHeight
}, 200);
$(filterTypeWrapper).find('.filter-btn').removeClass('active');
$(filterBtn).addClass('active');
}
*/
/*************Search Page Functions End*****************/
/*************Tabs on small Screen Functions*********/
function tabs() {
	tabsInitialized = true;
	var tabs = $('.tab-btn');
	var tabActive = $('.tab-btn.active');
	var tabTxt = $(tabs).find('.tab-text');
	$(tabTxt).each(function() {
		var refTo = $(this).attr('href');
		$(refTo).addClass('hidden');
	});
	var tabContentActive = $(tabActive).find('.tab-text').attr('href');
	$(tabContentActive).removeClass('hidden').addClass('active');
	$(tabs).click(function() {
		if ($(this).is(tabActive)) {
			return;
		} else {
			$(tabActive).removeClass('active');
			$(tabContentActive).removeClass('active').addClass('hidden');
			tabActive = $(this);
			$(tabActive).addClass('active');
			var tabContent = $(tabActive).find('.tab-text').attr('href');
			tabContentActive = $(tabContent);
			$(tabContentActive).addClass('active').removeClass('hidden');
			// resize related tiles if tab is opened
			if ($(window).width() <= 440 && $(tabContentActive).is('.related-tile-wrapper')) {
				resizeTiles();
			}
			//Prevent scrolling on click
			return false;
		}
	});
}

function removetabs() {
	tabsInitialized = false;
	var tabs = $('.tab-btn');
	var tabTxt = $(tabs).find('.tab-text');
	$(tabTxt).each(function() {
		var refTo = $(this).attr('href');
		$(refTo).removeClass('hidden');
	});
}

/*************Tabs on small Screen Functions End*********/
/*************Filter Toggle small Screen Functions End*********/
function filterToggle() {
	filterInitialized = true;
	var toggleTo;
	var filterWrapper = $('.filter-wrapper');
	filterHeight = parseInt($(filterWrapper).height());
	var filterWrapperBox = parseInt($(filterWrapper).css('padding-bottom').replace(/[^-\d\.]/g, ''));
	filterWrapperBox = filterWrapperBox + parseInt($(filterWrapper).css('padding-top').replace(/[^-\d\.]/g, ''));
	var filterToggleBtn = $('.filter-toggle-btn');
	var filterToggleBtnHeight = $(filterToggleBtn).height();
	var filterToggleBox = parseInt($(filterToggleBtn).css('padding-top').replace(/[^-\d\.]/g, ''));
	filterToggleBox = filterToggleBox + parseInt($(filterToggleBtn).css('padding-bottom').replace(/[^-\d\.]/g, ''));
	filterToggleBtnHeight = filterToggleBox + parseInt(filterToggleBtnHeight);
	filterHeight = filterHeight + filterWrapperBox + filterToggleBtnHeight / 2;

	$(filterWrapper).addClass('expanded');
	$(filterToggleBtn).click(function() {
		if ($(filterWrapper).hasClass('expanded')) {
			toggleTo = filterToggleBtnHeight;
		} else if ($(filterWrapper).not('.expanded')) {
			toggleTo = filterHeight;
		}
		$(filterWrapper).animate({
			height : toggleTo
		}, 200).toggleClass('expanded');
	});
}

/*************Filter Toggle small Screen Functions End*********/
/*************Resize Tile small Screen Functions*********/
//Adjust tile height on small screens to keep ratio
function resizeTiles() {
	tileHeightChanged = true;
	var tile = $('.tile');
	var tileWdth = $(tile).width();
	var tileHght = tileWdth / 2.035;
	$(tile).each(function() {
		if ($(this).hasClass('text-tile') == false && $(this).hasClass('topic-fb-tile') == false) {
			$(this).css('height', tileHght);
		}
	});
}

function clearFilterToggle() {
	var filterWrapper = $('.filter-wrapper');
	$(filterWrapper).removeAttr('style');
}

/*************Resize Tile small Screen Functions End*********/
/*************Filter Range Slider Functions *****************/
function createLabels(semRangeValue) {
	$(label_left).appendTo('#filter-range-slider-label');
	$(label_right).appendTo('#filter-range-slider-label');
	for (var i = 0; i <= semRangeText.length; i++) {
		if (semRangeValue[0] == i) {
			$(label_left).text(semRangeText[i]);
		}
		if (semRangeValue[1] == i) {
			$(label_right).text(semRangeText[i]);
		}
	}
}

function filterRangeInit() {
	semRangeValue = $('#filter-range-slider').val();
	$(label_left).addClass('noUi-handle-lower-label');
	$(label_right).addClass('noUi-handle-upper-label');
	$(label_left).addClass('noUi-handle-label');
	$(label_right).addClass('noUi-handle-label');
	$(label_left).appendTo('#filter-range-slider-label');
	$(label_right).appendTo('#filter-range-slider-label');
	for (var i = 0; i <= semRangeText.length; i++) {
		if (semRangeValue[0] == i) {
			$(label_left).text(semRangeText[i]);
		}
		if (semRangeValue[1] == i) {
			$(label_right).text(semRangeText[i]);
		}
	}
}

/************Filter Range Slider Functions End*********/
function hideFocus() {
	var inpt = $('input');
	$(inpt).blur();
}

/***************Overlay From Content Toggle**************/
//Display ThankYou message 
function overlayContentToggle() {
	var overlayContent = $('.is-active').find('.modal-content');
	$(overlayContent).each(function() {
		$(this).find('.wpcf7-display-none').css('display', 'none');
		$(this).toggleClass('hidden');
	});
}

/***************Overlay From Content Toggle End**************/

$(function() {
	FastClick.attach(document.body);
});
$(function() {
	$('figure.responsive').picture();
});
